version: '3.8'

services:
  flask-server:
    container_name: flask_container
    build: 
      context: ./static
      dockerfile: Dockerfile
    image: flask-demo:latest
    environment:
      - REDIS_HOST=redis-server
    networks:
      - flask-network
    ports:
      - 8080:5000

  redis-server:
    container_name: redis_container
    image: redis:latest
    networks:
      - flask-network

networks:
  flask-network:
    